### PR TITLE
Close icon of all screens inside registration workflow should reset data

### PR DESCRIPTION
**Pull request by ektaghag-eaton**
Fixes 5523 .

#### Changes proposed in this Pull Request:

-
-
-

#### Screenshots / Screen Recording (if applicable)

- 

https://github.com/etn-ccis/blui-react-native-workflows/assets/133877691/ee50eced-8083-4859-9c71-7b4ed0fca225

#### To Test:

-

#### Any specific feedback you are looking for?

- Test the Custom screen and Other screens close, the back icon clears data.

### CODE REVIEW

**Comment by JeffGreiner-eaton** [comment]
This seems good, I didn't look at the code but when I navigate from custom screen back to eula its skipped and I land on main screen.


https://github.com/etn-ccis/blui-react-native-workflows/assets/119693939/1fa4246d-4004-402c-a882-c1f8bc9ee0c2

**Review by surajeaton — COMMENTED** [review]
Please resolve the conflicts.

**Comment by ektaghag-eaton** [comment]
HI @surajeaton , please review.

**Review by surajeaton — APPROVED** [review]
Looks good.

**Pull request merged**
