### PR TITLE
update i18n instance

### PR DESCRIPTION
**Pull request by ArshdeepSingh3-eaton**
Fixes # .
updated to code to support system default language if available
updated the code to save user language preference

#### Changes proposed in this Pull Request:

-
-
-

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

-

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Review by surajeaton — COMMENTED** [review]
Lint is failing.

**Comment by JeffGreiner-eaton** [comment]
Should anything else be translated within other example screens/ registration workflow?

**Comment by ArshdeepSingh3-eaton** [comment]
the full screens are getting translated
the change was to persist the language selection

**Review by JeffGreiner-eaton — APPROVED** [review]
changes look good

**Pull request merged**
