### PR TITLE
Fix button should be disable when required prop is invalid

### PR DESCRIPTION
**Pull request by ektaghag-eaton**
Fixes BLUI 4726 .

#### Changes proposed in this Pull Request:

-  Fix mentioned issue [276](https://github.com/etn-ccis/blui-react-native-workflows/issues/276)
-
-

#### Screenshots / Screen Recording (if applicable)
Oct-04-2023 12-54-58

- uncomment the below lines from `App.tsx`
`import { CustomAccountDetails, CustomAccountDetailsTwo } from './src/screens/CustomRegistrationForm';`

`customAccountDetails={[
                { component: CustomAccountDetails },
                {
                    title: 'Job Info',
                    instructions: 'Enter your employment information below.',
                    component: CustomAccountDetailsTwo,
                },
            ]}
  `

#### To Test:

- Test registration workflow. In this scenario, the Country should not be empty. If it is empty then the Next button will be disabled.

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Review by surajeaton — COMMENTED** [review]
Please update changelog.

**Review by surajeaton — COMMENTED** [review]
After following the test instructions, I found this:

https://github.com/etn-ccis/blui-react-native-workflows/assets/120575281/6b8c9a14-f4fc-409e-9b1a-09034a836369

**Comment by manojleaton** [comment]
After clicked on Next button in AccountDetails screen, Next button is enabled initially in Job Info screen as well. Is it a expected behaviour?

**Comment by huayunh** [comment]
The expected behavior is that by default, all required fields must be filled in before users may progress to the next screen, and the control of enable/disabling the next button can be overridden by the adopter team if desired.

**Comment by ektaghag-eaton** [comment]
> After following the test instructions, I found this:
> 
>  Screen.Recording.2023-10-10.at.1.40.33.PM.mov

Fixed issue. Please review.

**Review by surajeaton — DISMISSED** [review]
Looks good.

**Review by surajeaton — COMMENTED** [review]
Button is getting enabled when start typing Country code and no Currency:

https://github.com/etn-ccis/blui-react-native-workflows/assets/120575281/1342166e-952f-4f54-af39-b52f8cba1c12

**Comment by ektaghag-eaton** [comment]
> Button is getting enabled when start typing Country code and no Currency:
> 
>  Screen.Recording.2023-10-11.at.4.02.24.PM.mov

Currency is optional. Only Country field is required in this scenario. You can update here https://github.com/etn-ccis/blui-react-native-workflows/blob/dev/login-workflow/example/src/screens/CustomRegistrationForm.tsx#L49 to check other scenarios.

**Review by surajeaton — APPROVED** [review]
Looks good.

**Pull request merged**
