### PR TITLE
update example app

### PR DESCRIPTION
**Pull request by ArshdeepSingh3-eaton**
Fixes # .

#### Changes proposed in this Pull Request:

-
-
-

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

-

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Comment by ektaghag-eaton** [comment]
Hi @ArshdeepSingh3-eaton, please take the latest pull from release/R31 to install husky on your local.

**Review by ektaghag-eaton — COMMENTED** [review]
Screenshot 2024-01-19 at 3 12 20 PM
I am getting this error while running an example app in iOS. Do I need to re-install cocoapods?

**Comment by joebochill** [comment]
I am getting this error while running an example app in iOS. Do I need to re-install cocoapods?

This is related to this recent change for react-native 0.73.2. They changed the download location for boost (https://github.com/facebook/react-native/issues/42180), and the new location appears to be blocked by IT. You may need to raise a ticket with IT to unblock it.

image


In the meantime, you can reverse the change mentioned in that issue since the original JFrog mirror appears to be back up and running.

**Comment by joebochill** [comment]
@ArshdeepSingh3-eaton version 6.9 of typescript-eslint introduced new configuration options for the naming-convention rule (added separate configuration options for default and imports). You can fix the errors by adding definitions to the "rules" entry (we should also do this at the root project level, or combine the lint configuration and have the root lint command also scan the example folder instead of having separate configs for the package and the example). Please also log an issue on the blui-code-standards repo for us to update to the lastest versions of ESLint and make this rule change.

The eslintrc file should look like:
```diff
module.exports = {
    root: true,
    parser: '@typescript-eslint/parser',
    extends: ['@brightlayer-ui/eslint-config/tsx'],
    parserOptions: {
        project: './tsconfig.json',
    },
+   plugins: ['react-hooks'],
+   rules: {
+       'react-hooks/rules-of-hooks': 'error', // Checks rules of Hooks
+       'react-hooks/exhaustive-deps': 'warn', // Checks effect dependencies
+       'react/display-name': 'off',
+       '@typescript-eslint/naming-convention': [
+           "error",
+           {
+               selector: 'default',
+               format: ['camelCase', 'PascalCase'],
+           },
+           {
+               selector: 'variable',
+               format: ['camelCase', 'UPPER_CASE', 'PascalCase'],
+           },
+           {
+               selector: 'property',
+               format: ['camelCase', 'UPPER_CASE', 'PascalCase'],
+           },
+           {
+               selector: 'property',
+               format: null,
+               modifiers: ['requiresQuotes'],
+           },
+           {
+               selector: 'enumMember',
+               format: ['UPPER_CASE'],
+           },
+           {
+               selector: 'parameter',
+               format: ['camelCase'],
+               leadingUnderscore: 'allow',
+           },
+           {
+               selector: 'memberLike',
+               modifiers: ['private'],
+               format: ['camelCase'],
+               leadingUnderscore: 'require',
+           },
+           {
+               selector: 'typeLike',
+               format: ['PascalCase'],
+           },
+           {
+              selector: 'import',
+               format: ['camelCase', 'PascalCase'],
+           },
+       ]
+   },
};
```

**Review by surajeaton — APPROVED** [review]
Example works fine and looks good.
Just fix the lint.

**Pull request merged**
