### PR TITLE
Configure the example project to use Open Sans font

### PR DESCRIPTION
**Pull request by ArshdeepSingh3-eaton**
Fixes # .
added OpenSans Font to Example Project
Update the text variant in verify code screen base

#### Changes proposed in this Pull Request:

-
-
-

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

-

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Review by surajeaton — COMMENTED** [review]
I think the goal was to update the variant only for Send Again button label.

Simulator Screenshot - iPhone 12 - 2024-03-13 at 16 15 37

**Comment by ArshdeepSingh3-eaton** [comment]
both of them were using a default variant so had to update both of them

**Comment by ArshdeepSingh3-eaton** [comment]
Screenshot 2024-03-14 at 5 04 16 PM

**Comment by JeffGreiner-eaton** [comment]
looks good.
- before
image

- after
image

**Review by JeffGreiner-eaton — APPROVED** [review]

**Pull request merged**
