### PR TITLE
User menu Item Translate

### PR DESCRIPTION
**Pull request by priyankakmEaton**
Fixes #5718

#### Changes proposed in this Pull Request:
- Add translations to the user menu list items as per language.

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

-

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Review by surajeaton — APPROVED** [review]
Looks good.

**Comment by JeffGreiner-eaton** [comment]
any concerns with this here?
image

**Comment by ektaghag-eaton** [comment]
> any concerns with this here? image

Hi @JeffGreiner-eaton , I will fix this issue in another PR.

**Review by JeffGreiner-eaton — APPROVED** [review]
nice, looks good

**Pull request merged**
