### PR TITLE
Feature/5216 implement error message box

### PR DESCRIPTION
**Pull request by surajeaton**
Fixes # BLUI-5216

#### Changes proposed in this Pull Request:

- Implement error message box
- Added test cases for error message box

#### Screenshots / Screen Recording (if applicable)
- 
Simulator Screenshot - iphone 12 pro - 2024-02-02 at 16 15 37

#### To Test:
For Testing, please update the existing WorkflowCardBody in the example with 
` <WorkflowCardBody>
                        <>
                            {hasError && (
                                <ErrorMessageBox
                                    title={'Error!'}
                                    errorMessage={'Error Message'}
                                    onClose={() => setHasError(false)}
                                />
                            )}
                            <TextInput
                                label="TextInput"
                                mode="flat"
                                left={<TextInput.Icon icon="email" />}
                                right={<TextInput.Icon icon="menu-down" />}
                                value={errorFilledText}
                                underlineColor={theme.colors.surface}
                                onChangeText={(value: string): void => {
                                    setErrorFilledText(value);
                                    setHasError(value.length > 4);
                                }}
                                error={hasError}
                            />
                            <HelperText type="error" visible={hasError} style={{ marginBottom: 8 }}>
                                
                                Error Message
                            </HelperText>
                        </>
                    </WorkflowCardBody>`

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Comment by ArshdeepSingh3-eaton** [comment]
Everthing Looks good
just add documentation for the error Message

**Review by ektaghag-eaton — COMMENTED** [review]
Alignment is breaking when `dismissible={false}` for both LTR and RTL
Screenshot 2024-02-05 at 2 40 32 PM

**Comment by ektaghag-eaton** [comment]
Font size is not as per our React Workflows:

React workflow MessageBox
Screenshot 2024-02-05 at 2 48 41 PM

React Native workflow MessageBox:
Screenshot 2024-02-05 at 2 51 59 PM

Can you update it?

**Comment by surajeaton** [comment]
> Font size is not as per our React Workflows:
> 
> React workflow MessageBox Screenshot 2024-02-05 at 2 48 41 PM
> 
> React Native workflow MessageBox: Screenshot 2024-02-05 at 2 51 59 PM
> 
> Can you update it?

Done. Please review:
RTL
Simulator Screenshot - iphone 12 pro - 2024-02-05 at 15 34 35

dismissable = {false}
Simulator Screenshot - iphone 12 pro - 2024-02-05 at 15 35 05

**Review by ektaghag-eaton — APPROVED** [review]

**Comment by surajeaton** [comment]
> Member

We are not going to add a single doc for all error management components/contexts

**Pull request merged**
