### PR TITLE
Passed message in success screen as jsx element

### PR DESCRIPTION
**Pull request by surajeaton**
Fixes # BLUI-5498

#### Changes proposed in this Pull Request:

- Passed success screen message as jsx element
- Updated success screen type
- Updated translation keys

#### Screenshots / Screen Recording (if applicable)

- 
Simulator Screenshot - iPhone 12 - 2024-03-12 at 14 31 05

#### To Test:

-

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Review by ektaghag-eaton — COMMENTED** [review]
Hi Suraj, I am not able to see organisation and email in bold.

RN Workflow
Screenshot 2024-03-12 at 5 58 17 PM


Attaching screenshot of React workflow success screen for reference
Screenshot 2024-03-12 at 5 56 54 PM

**Comment by JeffGreiner-eaton** [comment]
I have something different going on....
image

**Review by ektaghag-eaton — CHANGES_REQUESTED** [review]
remove extra space
<b>{`${String(organization)}`}</b> org.

**Comment by surajeaton** [comment]
> remove extra space {`${String(organization)}`} org.

We intentionally added extra space, to add after `added to the` text

**Comment by ektaghag-eaton** [comment]
Can you update the screenshot in readme file?

**Review by ektaghag-eaton — APPROVED** [review]

**Pull request merged**
