### PR TITLE
Feat/5537 fix example app

### PR DESCRIPTION
**Pull request by ektaghag-eaton**
#### Changes proposed in this Pull Request:

- [X] application loads user is not authenticated by default
- [X] Use Login base screen is displayed, which should have
- [X] a mock Login button which simply toggles the user authenticated status
- [X] a dummy link to reset password
- [X] a dummy link to Register which loads the registration workflow route
- [X] Click the dummy link to ResetPassword / Forgot password / Contact support loads respective screen
- [X] Closing the reset password screen pops it off the navigation stack and we should be back at the dummy login screen.

#### Screenshots / Screen Recording (if applicable)

-
simulator_screenshot_40ADAAB2-D99E-433B-BAAE-96DF5FCF9F26

#### To Test:

-

#### Any specific feedback you are looking for?

-

### CODE REVIEW

**Comment by JeffGreiner-eaton** [comment]
looks good. 
You can update home.tsx to uppercase Home.tsx and update drawer for correct active item. (if you are viewing dashboard page the locations is active in drawer and same for locations in view and dashboard active.

Do we know why all the nav.navigate and navigation.navigate in the screens/components in example all seem to not like the string values for login, home, destination, openDrawer.....

**Comment by ektaghag-eaton** [comment]
> looks good. You can update home.tsx to uppercase Home.tsx and update drawer for correct active item. (if you are viewing dashboard page the locations is active in drawer and same for locations in view and dashboard active.
> 
> Do we know why all the nav.navigate and navigation.navigate in the screens/components in example all seem to not like the string values for login, home, destination, openDrawer.....

Hi @JeffGreiner-eaton, let me check.

**Comment by JeffGreiner-eaton** [comment]
Navigation looks good to other screens/workflows but the create account needs adjusted
image

**Comment by JeffGreiner-eaton** [comment]
I did notice when we toggle RTL>LTR we loose our remember me data. I don't think this is an issue considering we rerender the app and the refresh drops the data.

**Comment by JeffGreiner-eaton** [comment]
Looks like the app isn't finding device language. Changing device language to anything other than english and reloading app/installing displays login screen in english. Do we have everything from here https://github.com/etn-ccis/blui-react-native-workflows/pull/438

**Comment by JeffGreiner-eaton** [comment]
One last item,  user menu should be translated

**Comment by joebochill** [comment]
We need to prioritize getting this done and merged ASAP — the smoke test story should ideally be testing the application after it has been set up correctly, otherwise we are. going to have to go back and check it again. Let's get the routing pieces finalized and working — translations are a minor detail that can be covered in a follow-up PR. But we absolutely must get the structure finished as soon as we can.

**Comment by ArshdeepSingh3-eaton** [comment]
fix the linting error

**Review by ArshdeepSingh3-eaton — DISMISSED** [review]

**Comment by JeffGreiner-eaton** [comment]
Change password from user menu throws error
image

Changing to RTL and selecting logout throws error
image

Remember me not working now

**Comment by ektaghag-eaton** [comment]
Closing this PR, and open new PR https://github.com/etn-ccis/blui-react-native-workflows/pull/457

**Pull request closed without merging**
